2022-04-13 20:56:50 INFO     root  - Starting Rasa server on http://localhost:5005
2022-04-13 20:56:50 INFO     rasa.model  - Loading model models/20220407-003909.tar.gz...
/home/botL/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:447: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/cond_grad/Identity_1:0", shape=(None,), dtype=int64), values=Tensor("gradients/cond_grad/Identity:0", shape=(None,), dtype=float32), dense_shape=Tensor("gradients/cond_grad/Identity_2:0", shape=(1,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
/home/botL/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:447: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/cond_1_grad/Identity_1:0", shape=(None,), dtype=int64), values=Tensor("gradients/cond_1_grad/Identity:0", shape=(None,), dtype=float32), dense_shape=Tensor("gradients/cond_1_grad/Identity_2:0", shape=(1,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
/home/botL/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:447: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/cond_2_grad/Identity_1:0", shape=(None,), dtype=int64), values=Tensor("gradients/cond_2_grad/Identity:0", shape=(None,), dtype=float32), dense_shape=Tensor("gradients/cond_2_grad/Identity_2:0", shape=(1,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
2022-04-13 20:57:05 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2022-04-13 20:57:13 INFO     root  - Rasa server is up and running.
2022-04-13 21:45:26 INFO     root  - Starting Rasa server on http://localhost:5005
2022-04-13 21:45:26 INFO     rasa.model  - Loading model models/20220407-003909.tar.gz...
2022-04-13 21:45:40 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_hello_world2'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_setIdDeputado'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_mostraDados'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_mostra_resumo'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_mostra_resumo_partido'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_mostraPartidoDeputado'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_mostraSituacao'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_mostraListaPartidos'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Re-registered function for 'action_mostraListaPartidos'.
2022-04-13 21:45:40 INFO     rasa_sdk.executor  - Registered function for 'action_mostraMembrosPartido'.
2022-04-13 21:45:40 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
/home/botL/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:447: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/cond_grad/Identity_1:0", shape=(None,), dtype=int64), values=Tensor("gradients/cond_grad/Identity:0", shape=(None,), dtype=float32), dense_shape=Tensor("gradients/cond_grad/Identity_2:0", shape=(1,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
/home/botL/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:447: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/cond_1_grad/Identity_1:0", shape=(None,), dtype=int64), values=Tensor("gradients/cond_1_grad/Identity:0", shape=(None,), dtype=float32), dense_shape=Tensor("gradients/cond_1_grad/Identity_2:0", shape=(1,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
/home/botL/lib/python3.8/site-packages/tensorflow/python/framework/indexed_slices.py:447: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/cond_2_grad/Identity_1:0", shape=(None,), dtype=int64), values=Tensor("gradients/cond_2_grad/Identity:0", shape=(None,), dtype=float32), dense_shape=Tensor("gradients/cond_2_grad/Identity_2:0", shape=(1,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
2022-04-13 21:45:41 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2022-04-13 21:45:48 INFO     root  - Rasa server is up and running.
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
2022-04-14 13:07:47 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_mostra_resumo'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/rasa/core/actions/action.py", line 685, in run
    response = await self.action_endpoint.request(
  File "/home/botL/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 172, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'<!DOCTYPE html><html lang=en><meta charset=UTF-8><title>\xe2\x9a\xa0\xef\xb8\x8f 500 \xe2\x80\x94 Internal Server Error</title>\n<style>\n        html { font-family: sans-serif }\n        h2 { color: #888; }\n        .tb-wrapper p { margin: 0 }\n        .frame-border { margin: 1rem }\n        .frame-line > * { padding: 0.3rem 0.6rem }\n        .frame-line { margin-bottom: 0.3rem }\n        .frame-code { font-size: 16px; padding-left: 4ch }\n        .tb-wrapper { border: 1px solid #eee }\n        .tb-header { background: #eee; padding: 0.3rem; font-weight: bold }\n        .frame-descriptor { background: #e2eafb; font-size: 14px }\n    </style>\n<h1>\xe2\x9a\xa0\xef\xb8\x8f 500 \xe2\x80\x94 Internal Server Error</h1><p>The server encountered an internal error and cannot complete your request.\n''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/rasa/core/processor.py", line 772, in _run_action
    events = await action.run(
  File "/home/botL/lib/python3.8/site-packages/rasa/core/actions/action.py", line 709, in run
    raise RasaException("Failed to execute custom action.") from e
rasa.shared.exceptions.RasaException: Failed to execute custom action.
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/botL/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/home/botL/lib/python3.8/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/home/2021.2-DepBot/bot/actions/actions.py", line 118, in run
    texto2 = '- Nome Civil: ' + nomeCivil + '\n' + '- Nome Eleitoral: ' + nomeEleitoral + '\n' + '- Email: ' + email + '\n'+ '- Partido: ' + partido + '\n' + '- Sexo: ' + sexoT + '\n' + '- Escolaridade: ' + esolaridade + '\n' +  '- UF Nascimento: ' + ufNascimento + '\n' + '- MunicÃ­pio Nascimento: ' + municipioNascimento
TypeError: can only concatenate str (not "NoneType") to str
AVANTE
CIDADANIA
DC
DEM
MDB
NOVO
PATRI
PATRIOTA
PCB
PCdoB
PCO
PDT
PHS
PL
PMB
PMN
PODE
PP
PPL
PPS
PR
PRB
PROS
PRP
PRTB
PSB
PSC
PSD
PSDB
PSL
PSOL
PSTU
PT
PTB
PTC
PV
REDE
REPUBLICANOS
S.PART.
SOLIDARIEDADE
UNIÃƒO

